#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the stepPerms function below.
st = 1
stArr = {}

def stepPerms(n):
    if st in stArr:
        return stArr[st]
    elif st > n:
        return 0
    elif st == n:
        return 1
    else:
        val = stepPerms(st+1) + stepPerms(st+2) + stepPerms(st+3)
        stArr[st] = val
        return val 
    

if __name__ == '__main__':
    # fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = int(input())

    for s_itr in range(s):
        n = int(input())

        res = stepPerms(n)

        # fptr.write(str(res) + '\n')

    # fptr.close()

